name: test
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format-check

      - name: Run static analysis
        run: npm run lint

      - name: Build this package
        run: npm run build

      - name: Build this package for distribution
        run: npm run package

      - name: Upload this project as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: project
          if-no-files-found: error
          path: |
            *
            !lib/
            !node_modules/

  check-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download the project artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: project

      - name: Check if the distribution is up to date
        run: git diff --exit-code HEAD

  standard-usage:
    needs: build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Download the project artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: project

      - name: Configure, build, and test the sample project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: sample
          generator: Ninja
          cxx-compiler: g++
          run-test: true

      - name: Upload the distribution with build as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist-with-build-${{ matrix.os }}
          if-no-files-found: error
          path: |
            .git/
            dist/
            sample/
            action.yml

      - name: Use this action
        uses: ./

  llvm-usage:
    needs: build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Download the project artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: project

      - name: Configure, build, and test the sample project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: sample
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          run-test: true

      - name: Use this action with llvm-cov as the gcov executable
        uses: ./
        with:
          gcov-executable: ${{ matrix.os == 'macos' && 'xcrun ' || '' }}llvm-cov gcov

  exclusion-usage:
    needs: build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Download the project artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: project

      - name: Configure, build, and test the sample project
        uses: threeal/cmake-action@v1.1.0
        with:
          source-dir: sample
          generator: Ninja
          cxx-compiler: g++
          args: -DTEST_EVEN=OFF -DTEST_ODD=OFF
          run-test: true

      - name: Use this action without an exclusion
        id: failed_step
        continue-on-error: true
        uses: ./
        with:
          root: sample
          fail-under-line: 100

      - name: Check if the previous step did fail
        run: ${{ steps.failed_step.outcome == 'failure' && true || false }}

      - name: Use this action without an exclusion but with a lower fail threshold
        uses: ./
        with:
          root: sample
          fail-under-line: 50

      - name: Use this action with an exclusion
        uses: ./
        with:
          root: sample
          exclude: sample/include/*
          fail-under-line: 100

  coveralls-usage:
    needs: standard-usage
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Download the distribution with build artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: dist-with-build-${{ matrix.os }}

      - name: Use this action to generate a Coveralls report
        uses: ./
        with:
          coveralls-out: coveralls.json

      - name: Check if that Coveralls report does exist
        run: cat coveralls.json

      - name: Use this action to generate and send another Coveralls report
        uses: ./
        with:
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use this action to generate and send another Coveralls report on a specified output
        uses: ./
        with:
          coveralls-out: coveralls-2.json
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if that Coveralls report does exist
        run: cat coveralls-2.json
