name: test
on:
  workflow_dispatch:
  push:
jobs:
  use-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Build and test example project
        run:  |
          cmake test -B build
          cmake --build build
          ctest --test-dir build

      - name: Use this action
        uses: ./

  use-action-llvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Build and test example project
        run:  |
          cmake test -B build -DCMAKE_CXX_COMPILER=clang++
          cmake --build build
          ctest --test-dir build

      - name: Use this action
        uses: ./
        with:
          gcov-executable: llvm-cov gcov

  use-action-from-different-root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Build and test example project
        working-directory: test
        run:  |
          cmake . -B build
          cmake --build build
          ctest --test-dir build

      - name: Use this action from build root
        id: failed_step
        continue-on-error: true
        uses: ./
        with:
          root: test/build
          fail-under-line: 100

      - name: Check if previous step is failing
        run: ${{ steps.failed_step.outcome == 'failure' && true || false }}

      - name: Use this action from build root but without fail threshold
        uses: ./
        with:
          root: test/build

      - name: Use this action from project root
        uses: ./
        with:
          root: test
          fail-under-line: 100

  use-action-with-exclusion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Build and test example project
        working-directory: test
        run:  |
          cmake . -B build -DTEST_EVEN=OFF -DTEST_ODD=OFF
          cmake --build build
          ctest --test-dir build

      - name: Use this action without exclusion
        id: failed_step
        continue-on-error: true
        uses: ./
        with:
          fail-under-line: 100

      - name: Check if previous step is failing
        run: ${{ steps.failed_step.outcome == 'failure' && true || false }}

      - name: Use this action without exclusion but with lower fail threshold
        uses: ./
        with:
          fail-under-line: 50

      - name: Use this action with exclusion
        uses: ./
        with:
          exclude: test/include/*
          fail-under-line: 100

  use-action-generate-coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Build and test example project
        run:  |
          cmake test -B build
          cmake --build build
          ctest --test-dir build

      - name: Use this action to generate Coveralls report
        uses: ./
        with:
          coveralls-out: coveralls.json

      - name: Check if Coveralls report exist
        run: cat coveralls.json

      - name: Use this action to generate and send Coveralls report
        uses: ./
        with:
          coveralls-send: true
          github-token: ${{ secrets.github_token }}

      - name: Use this action to generate and send Coveralls report on specified output
        uses: ./
        with:
          coveralls-out: coveralls-2.json
          coveralls-send: true
          github-token: ${{ secrets.github_token }}

      - name: Check if Coveralls report exist
        run: cat coveralls-2.json
